CREATE TABLE IF NOT EXISTS EMPLOYEE (
    EMP_ID SERIAL PRIMARY KEY, 
    SALARY INT, 
    DATE_OF_JOINING DATE
);

CREATE TABLE IF NOT EXISTS DOCTOR (
    EMP_ID INT PRIMARY KEY, 
    SPECIALTY VARCHAR(255), 
    MEDICAL_LICENSE_NO INT,
    FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE (EMP_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS NURSE (
    EMP_ID INT PRIMARY KEY,
    SHIFT_ASSIGNED VARCHAR(255),
    FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE (EMP_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PATIENT (
  PATIENT_ID SERIAL PRIMARY KEY,
  FIRST_NAME VARCHAR(255),
  LAST_NAME VARCHAR(255),
  DATE_OF_BIRTH DATE,
  HOUSE_NO VARCHAR(20),
  STREET_NAME VARCHAR(255),
  LANDMARK VARCHAR(255),
  CITY VARCHAR(255),
  PINCODE INT
);

CREATE TABLE IF NOT EXISTS PATIENT_CONTACT (
  PATIENT_ID INT,
  CONTACT_NUMBER VARCHAR(20),
  FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT (PATIENT_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS APPOINTMENT (
  APPOINTMENT_ID SERIAL PRIMARY KEY,
  PATIENT_ID INT,
  DOCTOR_ID INT,
  DATE_OF_VISIT DATE DEFAULT CURRENT_DATE,
  REASON_OF_VISIT VARCHAR(255),
  TIMESLOT TIME,
  FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT (PATIENT_ID) ON DELETE CASCADE,
  FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTOR (EMP_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ROOM (
  ROOM_NUMBER SERIAL PRIMARY KEY,
  TYPE VARCHAR(255),
  CAPACITY INT CHECK (CAPACITY > 0)
);

CREATE TABLE IF NOT EXISTS BED (
  BED_ID SERIAL PRIMARY KEY,
  ROOM_NUMBER INT NOT NULL,
  STATUS VARCHAR(255),
  PATIENT_ID_OCCUPYING INT,
  FOREIGN KEY (ROOM_NUMBER) REFERENCES ROOM (ROOM_NUMBER) ON DELETE CASCADE,
  FOREIGN KEY (PATIENT_ID_OCCUPYING) REFERENCES PATIENT (PATIENT_ID) ON DELETE SET NULL
);